=== jtlai0921/AEL015000/書附光碟/ViLLE_VB/dat1/ville.dtd
<!ELEMENT InitData (Language, Popup, Highlight, Objects, Width, Height,ProgLang)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT Popup (#PCDATA)>
<!ELEMENT Highlight (#PCDATA)>
<!ELEMENT Objects (#PCDATA)>
<!ELEMENT Width (#PCDATA)>
<!ELEMENT Height (#PCDATA)>
<!ELEMENT ProgLang (#PCDATA)>

=== jtlai0921/AEL015000/書附光碟/ViLLE_VB/dat/ville.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE InitData SYSTEM "ville.dtd">
<InitData>
	<Language>1</Language>
	<Popup>1</Popup>
	<Highlight>1</Highlight>
	<Objects>1</Objects>
	<Width>1280</Width>
	<Height>694</Height>
	<ProgLang>Visual Basic</ProgLang>
</InitData>
