=== jtlai0921/AEL015000/書附光碟/ViLLE_VB/dat/syntax_new.dtd
<!ELEMENT Syntax (Language,Typed,Commands)>
<!ELEMENT Language (#PCDATA)>
<!ELEMENT Typed (#PCDATA)>
<!ELEMENT Commands (Command)*>
<!ELEMENT Command (Id, Keys, Code)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Keys (Key)*>
<!ELEMENT Key (#PCDATA)>
<!ELEMENT Code (#PCDATA)>

=== jtlai0921/AEL015000/書附光碟/ViLLE_VB/dat1/syntax_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Syntax SYSTEM "syntax_new.dtd">
<Syntax>
	<Language>New Language</Language>
	<Typed>true</Typed>
	<Commands>
      <Command>
        <Id>0</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>1</Id>
        <Keys>
          <Key>for</Key>
          <Key>--</Key>
          <Key>&gt;=</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &gt;= @2; @0--){</Code>
      </Command>
      <Command>
        <Id>2</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>3</Id>
        <Keys>
          <Key>for</Key>
          <Key>++</Key>
          <Key>&lt;=</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &lt;= @2; @0++){</Code>
      </Command>
      <Command>
        <Id>4</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>5</Id>
        <Keys>
          <Key>for</Key>
          <Key>--</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &gt; @2; @0--){</Code>
      </Command>
      <Command>
        <Id>6</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>7</Id>
        <Keys>
          <Key>for</Key>
          <Key>++</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &lt; @2; @0++){</Code>
      </Command>
      <Command>
        <Id>8</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>9</Id>
        <Keys>
          <Key>for</Key>
          <Key>&gt;=</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &gt;= @2; @0 = @0-@3){</Code>
      </Command>
      <Command>
        <Id>10</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>11</Id>
        <Keys>
          <Key>for</Key>
          <Key>&lt;=</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &lt;= @2; @0 = @0+@3){</Code>
      </Command>
      <Command>
        <Id>12</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>13</Id>
        <Keys>
          <Key>for</Key>
          <Key>&gt;</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &gt; @2; @0 = @0-@3){</Code>
      </Command>
      <Command>
        <Id>14</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>15</Id>
        <Keys>
          <Key>for</Key>
          <Key>&lt;</Key>
          <Key>(</Key>
          <Key>)</Key>
        </Keys>
        <Code>for (@0 = @1; @0 &lt; @2; @0 = @0+@3){</Code>
      </Command>
      <Command>
        <Id>16</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>17</Id>
        <Keys>
          <Key>while</Key>
          <Key>(</Key>
          <Key>)</Key>
          <Key>{</Key>
        </Keys>
        <Code>while (@0){</Code>
      </Command>
      <Command>
      	<Id>18</Id>
      	<Keys>
      		<Key>}</Key>
      		<Key>while</Key>
      		<Key>(</Key>
      		<Key>)</Key>
      		<Key>;</Key></Keys>
      	<Code>} while (@0);</Code>
      </Command>
      <Command>
      	<Id>19</Id>
      	<Keys>
      		<Key>do</Key>
      		<Key>{</Key></Keys>
      	<Code>do {</Code>
      </Command>
      <Command>
        <Id>20</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>21</Id>
        <Keys>
          <Key>else</Key>
          <Key>if</Key>
          <Key>{</Key>
        </Keys>
        <Code>else if (@0){</Code>
      </Command>
      <Command>
        <Id>22</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>23</Id>
        <Keys>
          <Key>if</Key>
          <Key>{</Key>
        </Keys>
        <Code>if (@0){</Code>
      </Command>
      <Command>
        <Id>24</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>25</Id>
        <Keys>
          <Key>else</Key>
          <Key>{</Key>
        </Keys>
        <Code>else{</Code>
      </Command>
      <Command>
        <Id>26</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>27</Id>
        <Keys>
          <Key>public</Key>
          <Key>static</Key>
          <Key>main</Key>
        </Keys>
        <Code>public static void main(String[] args){</Code>
      </Command>
      <Command>
        <Id>28</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>29</Id>
        <Keys>
          <Key>public</Key>
          <Key>static</Key>
          <Key>void</Key>
          <Key>{</Key>
        </Keys>
        <Code>public static void @0(@1){</Code>
      </Command>
      <Command>
        <Id>30</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>31</Id>
        <Keys>
          <Key>private</Key>
          <Key>static</Key>
          <Key>void</Key>
          <Key>{</Key>
        </Keys>
        <Code>private static void @0(@1){</Code>
      </Command>
      <Command>
        <Id>32</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>33</Id>
        <Keys>
          <Key>public</Key>
          <Key>void</Key>
        </Keys>
        <Code>public void @0(@1){</Code>
      </Command>
      <Command>
        <Id>34</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>35</Id>
        <Keys>
          <Key>private</Key>
          <Key>void</Key>
        </Keys>
        <Code>private void @0(@1){</Code>
      </Command>
      <Command>
        <Id>36</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>37</Id>
        <Keys>
          <Key>public</Key>
          <Key>class</Key>
        </Keys>
        <Code>public class @0{</Code>
      </Command>
      <Command>
        <Id>38</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>39</Id>
        <Keys>
          <Key>private</Key>
          <Key>class</Key>
        </Keys>
        <Code>private class @0{</Code>
      </Command>
      <Command>
        <Id>40</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>41</Id>
        <Keys>
          <Key>class</Key>
        </Keys>
        <Code>class @0{</Code>
      </Command>
      <Command>
        <Id>42</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>43</Id>
        <Keys>
          <Key>public</Key>
          <Key>static</Key>
          <Key>{</Key>
        </Keys>
        <Code>public static @0 @1(@2){</Code>
      </Command>
      <Command>
        <Id>44</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>45</Id>
        <Keys>
          <Key>private</Key>
          <Key>static</Key>
          <Key>{</Key>
        </Keys>
        <Code>private static @0 @1(@2){</Code>
      </Command>
      <Command>
        <Id>46</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>47</Id>
        <Keys>
          <Key>public</Key>
          <Key>{</Key>
        </Keys>
        <Code>public @0 @1 (@2){</Code>
      </Command>
      <Command>
        <Id>48</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>49</Id>
        <Keys>
          <Key>private</Key>
          <Key>{</Key>
        </Keys>
        <Code>private @0 @1 (@2){</Code>
      </Command>
      <Command>
        <Id>50</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>51</Id>
        <Keys>
          <Key>switch</Key>
        </Keys>
        <Code>switch(@0){</Code>
      </Command>
      <Command>
        <Id>52</Id>
        <Keys>
          <Key>}</Key>
        </Keys>
        <Code>}</Code>
      </Command>
      <Command>
        <Id>53</Id>
        <Keys>
          <Key>public</Key>
          <Key>{</Key>
        </Keys>
        <Code>public @0(@1){</Code>
      </Command>
      <Command>
        <Id>54</Id>
        <Keys>
          <Key>return</Key>
        </Keys>
        <Code>return @0;</Code>
      </Command>
      <Command>
        <Id>55</Id>
        <Keys>
          <Key>System.out.println</Key>
        </Keys>
        <Code>System.out.println(@0);</Code>
      </Command>
	  <Command>
        <Id>55</Id>
        <Keys>
          <Key>System.out.print</Key>
        </Keys>
        <Code>System.out.print(@0);</Code>
      </Command>
      <Command>
        <Id>56</Id>
        <Keys>
          <Key>else</Key>
          <Key>if</Key>
        </Keys>
        <Code>else if (@0)</Code>
      </Command>
      <Command>
        <Id>57</Id>
        <Keys>
          <Key>if</Key>
          <Key>(</Key>
        </Keys>
